name: Deploy to Render

on:
  push:
    branches:
      - deploy  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Render
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
